### PR TITLE
add global aliases to auto-generated code

### PR DESCRIPTION
**Pull request by Ami-Coen**
## Description

Add global aliases to auto-generated code.

In project that implicit using was disabled, ClassMemberAttribute may fail to build with CS0246 error because that auto-generate code without System namespace usings.

### CODE REVIEW

**Comment by ufcpp** [comment]
I understand the need for `System.`. Do you also need `global::`? Did you have any conflicts?

**Comment by Ami-Coen** [comment]
> I understand the need for `System.`. Do you also need `global::`? Did you have any conflicts?

Most problems, including the one I've run into, can be fixed by just adding `System.`.
However, given the best practices in auto-generating code, I think it's safer to add `global::` (although I think it's rare for developers to define their own System class today).

As for me, I am not particular here. If the reference to `System.` is properly added, then my problems will be solved.

**Comment by ufcpp** [comment]
>  given the best practices in auto-generating code, I think it's safer to add `global::`

I thought so too, but `GeneratedRegex`, for example, doesn't have `global::` for `System`. If either way looks ok, I don't like so long code, even for generated source codes.

**Comment by ufcpp** [comment]
It's just my preference. I don't mind merging them as they are now.

**Comment by Ami-Coen** [comment]
> I thought so too, but GeneratedRegex, for example, doesn't have global:: for System. If either way looks ok, I don't like so long code, even for generated source codes.
> It's just my preference. I don't mind merging them as they are now.

Thank you for your comment.
Indeed, considering the case of GeneratedRegex, there seems to be a tendency not to add `global::` to the auto-generated code.
Shall we close this PR and create a new one that adds only `System.` (since this branch is also named "add-global-alias")?

**Comment by ufcpp** [comment]
Either a new PR or a revised commit on this PR is fine.

**Comment by Ami-Coen** [comment]
> Either a new PR or a revised commit on this PR is fine.

Pushed revised commit on this PR.  https://github.com/ufcpp/ScribanSourceGenerator/pull/2/commits/117604cf6d151fe848431da9616e6309d88eb0fd

**Comment by ufcpp** [comment]
Thanks.

**Comment by ufcpp** [comment]
Released.
https://github.com/ufcpp/ScribanSourceGenerator/releases/tag/v1.1.0
https://www.nuget.org/packages/ScribanSourceGenerator/1.1.0

**Pull request merged**
